CREATE TABLE IF NOT EXISTS everkeep_backups (
  owner_key VARCHAR(64) PRIMARY KEY,
  state_json LONGTEXT NOT NULL,
  client_updated_at BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
